name: Test current-time action
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get current time
        uses: joaomaranhao/current-time@main
        id: current-time
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.time }}"
        run: echo $TIME